# Generated by Django 4.2 on 2023-04-29 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label_Product',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('category_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='название категории')),
            ],
            options={
                'verbose_name_plural': 'категории ',
            },
        ),
        migrations.CreateModel(
            name='product_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='main/static/images/', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/static/images/')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('xs', models.IntegerField()),
                ('s', models.IntegerField()),
                ('m', models.IntegerField()),
                ('l', models.IntegerField()),
                ('xl', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.label_product')),
            ],
        ),
        migrations.AddField(
            model_name='label_product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product_category', verbose_name='category'),
        ),
    ]
