# Generated by Django 4.1.7 on 2023-03-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
            ],
        ),
    ]
