# Generated by Django 4.2 on 2023-04-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='id',
        ),
        migrations.AddField(
            model_name='basket',
            name='users',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
