# Generated by Django 4.2 on 2023-04-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_basket_users_basket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('a', 'В обработке'), ('b', 'Доставляется'), ('c', 'Выполнен ')], default=4, max_length=1, verbose_name='статус'),
            preserve_default=False,
        ),
    ]
