# Generated by Django 4.2 on 2023-04-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_basket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='id',
            field=models.BigAutoField(auto_created=True, default=3, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basket',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
