# Generated by Django 4.2 on 2023-04-30 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_basket_id_alter_basket_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('a', 'В обработке'), ('b', 'Доставляется'), ('c', 'Выполнен ')], default='a', max_length=1, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='l',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='m',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='s',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='xs',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('a', 'В обработке'), ('b', 'Доставляется'), ('c', 'Выполнен ')], default='a', max_length=1, verbose_name='статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
